# defaults:
#     - data: dataset1
#       optional: true
project:
    name: temporal-consistency

data:
    name: elephant # rand
    sat: s2
    train_size: 0.7
    

model:
    name: ConvLSTM
    future_seq: 0

    tc: 0 

    batch_size: 128
    number_filters: 64
    input_channels: 3
    max_epoch: 100

    learning_rate: 0.01
    momentum: 0.9

experiment:
    note: new
    name: ${data.name}_${data.sat}_${model.name}_tc_${model.tc}_${experiment.note}
    output: ./outputs/${data.name}_${model.name}_${now:%Y%m%dT%H%M%S} #${defaults.0.data}

hydra:
    run:
        dir: ${experiment.output}