# defaults:
#     - data: dataset1
#       optional: true
project:
    name: temporal-consistency

data:
    name: Ljusdals # rand, Ljusdals, elephant
    folder: s1_data_kmap
    note: '20m'
    
    train_size: 0.7
    

model:
    name: ConvLSTM
    future_seq: 0

    tc: 0.5 # total_loss =  (1-cfg.model.tc) * dice_loss + cfg.model.tc * tc_loss

    batch_size: 128
    number_filters: 64
    input_channels: 3
    max_epoch: 100

    learning_rate: 0.1
    momentum: 0.9
    use_lr_scheduler: True

    inferPatchSize: 128
    logImgPerEp: 10
    warmup_coef: 2

    saveImgSglFlag: True # save single prediction image or not
    saveImgArrFlag: True # save arranged image array or not

experiment:
    note: bal
    name: ${data.name}_${data.folder}_${model.name}_tc_${model.tc}_${experiment.note}
    output: ./outputs/${experiment.name}_${now:%Y%m%dT%H%M%S} #${defaults.0.data}

hydra:
    run:
        dir: ${experiment.output}